# Generated by Django 3.2.15 on 2022-08-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subCat',
            field=models.TextField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
