# Generated by Django 3.2.15 on 2022-08-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220822_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='subCat',
            field=models.CharField(max_length=25),
        ),
    ]
