# Generated by Django 3.2.15 on 2022-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220822_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subCat',
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
