# Generated by Django 3.2.15 on 2022-08-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorImage',
            field=models.ImageField(default='', height_field=30, upload_to='', width_field=30),
            preserve_default=False,
        ),
    ]
