# Generated by Django 3.2.15 on 2022-10-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_authorimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authorImage',
            new_name='postImage',
        ),
    ]
