# Generated by Django 3.2.15 on 2022-10-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_authorimage_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(upload_to='static/image/post_img'),
        ),
    ]
