# Generated by Django 3.2.15 on 2022-10-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
