# Generated by Django 3.2.15 on 2022-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painter', models.CharField(max_length=25)),
                ('paint_title', models.CharField(max_length=30)),
                ('painting', models.ImageField(upload_to='static/image/painting')),
                ('slug', models.CharField(max_length=30)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
