# Generated by Django 3.2.15 on 2022-10-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_paint'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='branch',
            field=models.CharField(default='null', max_length=5),
            preserve_default=False,
        ),
    ]
